spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.108.67:3306/smartmeetingroom?useUnicode=true&characterEncoding=utf8
    username: root
    password: sunwang1
